/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  safelist: [
    'w-8',
    'h-8',
    'w-10',
    'h-10',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#FDFCF0',
        'on-secondary': '#FDFCF0',
        'secondary-fixed': '#F1E8D7',
        'on-primary-fixed': '#1A1A1A',
        'on-error-container': '#7A120C',
        background: '#FDFCF0',
        'on-tertiary-fixed-variant': '#7A3F23',
        'surface-container-low': '#F7F1E5',
        'surface-container': '#F1E8D7',
        'surface-container-lowest': '#FFFDF6',
        tertiary: '#FF8C5A',
        'tertiary-container': '#FFD9C8',
        'on-primary-container': '#1A1A1A',
        'surface-tint': '#0F5132',
        'on-primary': '#FDFCF0',
        'inverse-surface': '#1A1A1A',
        'on-primary-fixed-variant': '#4F2E8C',
        'on-surface-variant': '#4C443A',
        'primary-fixed-dim': '#D9BFF5',
        'outline-variant': '#6E665B',
        'primary-container': '#E6D0FF',
        'secondary-fixed-dim': '#DDD3B8',
        'surface-container-highest': '#DDD3B8',
        'on-error': '#FDFCF0',
        'on-surface': '#1A1A1A',
        primary: '#0F5132',
        outline: '#1A1A1A',
        'tertiary-fixed-dim': '#F2B08F',
        'on-tertiary-fixed': '#7A3F23',
        'surface-variant': '#E7DCCB',
        'surface-dim': '#E8DDC4',
        error: '#B42318',
        'on-secondary-fixed': '#1A1A1A',
        'on-secondary-container': '#1A1A1A',
        'on-background': '#1A1A1A',
        'error-container': '#FFE1DC',
        'surface-bright': '#FFFDF6',
        'surface-container-high': '#E8DDC4',
        'on-tertiary-container': '#1A1A1A',
        'primary-fixed': '#DCE9D2',
        secondary: '#1A1A1A',
        surface: '#FDFCF0',
        'inverse-primary': '#E6D0FF',
        'on-secondary-fixed-variant': '#1A1A1A',
        'on-tertiary': '#1A1A1A',
        'tertiary-fixed': '#FFD9C8',
        'secondary-container': '#F1E8D7',
        'peach-muted': '#FFCCBC',
        'chekhov-ice': '#DCE9D2',
        'ice-blue': '#E6D0FF',
        'scholar-teal': '#0F5132',
      },
      fontFamily: {
        headline: ['var(--font-newsreader)', 'serif'],
        body: ['var(--font-newsreader)', 'serif'],
        label: ['var(--font-jetbrains-mono)', 'monospace'],
      },
      borderRadius: {
        none: '0px',
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '0px',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
