export const SITE_NAME = 'Philosophy Spread';
export const SITE_DESCRIPTION =
  'Philosophy Spread explores timeless wisdom, logic modules, and philosophical insights. Join our community of thinkers.';
export const SITE_LOCALE = 'en_US';

const CONTENT_IMAGE_DIMENSIONS: Readonly<Record<string, { width: number; height: number }>> = {
  '/choice.avif': { width: 500, height: 333 },
  '/consciousness.avif': { width: 1024, height: 766 },
  '/boredom.png': { width: 1024, height: 732 },
  '/logic.avif': { width: 1045, height: 718 },
  '/metaphysics.avif': { width: 736, height: 414 },
  '/morality.avif': { width: 960, height: 1088 },
};

export function getImageDimensions(pathname: string): { width: number; height: number } | undefined {
  try {
    return CONTENT_IMAGE_DIMENSIONS[new URL(pathname, 'https://philosophyspread.live').pathname];
  } catch {
    return undefined;
  }
}

/**
 * The site is configured with `trailingSlash: 'always'`. Keep canonical URLs,
 * sitemap entries, and links generated by pages on that same policy. File
 * routes (for example `/sitemap.xml`) are intentionally left unchanged.
 */
export function withTrailingSlash(pathname: string): string {
  if (pathname === '/' || pathname.endsWith('/') || /\.[^/]+$/.test(pathname)) {
    return pathname;
  }

  return `${pathname}/`;
}

export function absoluteSiteUrl(pathname: string, siteUrl: URL): string {
  const url = new URL(pathname, siteUrl);
  url.pathname = withTrailingSlash(url.pathname);
  return url.toString();
}

/**
 * JSON-LD is embedded in a raw script element. Escaping `<`, `>`, and `&`
 * prevents data containing `</script>` (for example a user-supplied title)
 * from terminating the element before the JSON is parsed.
 */
export function serializeJsonLd(value: unknown): string {
  const serialized = JSON.stringify(value);
  if (serialized === undefined) {
    return '';
  }

  return serialized
    .replaceAll('<', '\\u003c')
    .replaceAll('>', '\\u003e')
    .replaceAll('&', '\\u0026');
}

export function truncateMetadata(value: string, maxLength: number): string {
  const normalized = value.replace(/\s+/g, ' ').trim();
  if (normalized.length <= maxLength) {
    return normalized;
  }

  const cutoff = Math.max(1, maxLength - 1);
  return `${normalized.slice(0, cutoff).trimEnd()}…`;
}
